kafka.bootstrapAddress: localhost:9092


spring:
  datasource:
    username: postgres
    password:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=test
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        temp:
          use_jdbc_metadata_defaults: false
        physical_naming_strategy: "org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy"
        implicit_naming_strategy: "org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy"

logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
server:
  port: 8082
